apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-svc
spec:
  replicas: 2
  selector:
    matchLabels: { app: pay-svc }
  template:
    metadata:
      labels: { app: pay-svc }
    spec:
      containers:
        - name: app
          image: pay-svc:local
          ports: [{ containerPort: 8080 }]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
