name: ci
on:
  pull_request:
  push: { branches: [main] }

jobs:
  test-sast-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - name: Unit tests
        run: bash scripts/test.sh
      - name: Semgrep SAST
        run: bash scripts/scan_sast.sh
      - name: Gitleaks
        run: bash scripts/scan_secrets.sh

  build-and-scan:
    runs-on: ubuntu-latest
    needs: [test-sast-secrets]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: bash scripts/build.sh
      - name: Trivy Image
        run: bash scripts/scan_image.sh

  iac-scan:
    runs-on: ubuntu-latest
    needs: [build-and-scan]
    steps:
      - uses: actions/checkout@v4
      - name: Trivy IaC
        run: bash scripts/scan_iac.sh
